-- MySQL Script generated by MySQL Workbench
-- Sat Feb 12 09:56:14 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema finalproject
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema finalproject
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `finalproject` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `finalproject` ;

-- -----------------------------------------------------
-- Table `finalproject`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `finalproject`.`users` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `EMAIL` VARCHAR(40) CHARACTER SET 'utf8' NOT NULL,
  `PASSWORD` VARCHAR(40) CHARACTER SET 'utf8' NOT NULL,
  `FIRSTNAME` VARCHAR(40) CHARACTER SET 'utf8' NOT NULL,
  `LASTNAME` VARCHAR(40) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `EMAIL_UNIQUE` (`EMAIL` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `finalproject`.`addresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `finalproject`.`addresses` (
  `USERID` INT NOT NULL,
  `ADDRESSONE` VARCHAR(40) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `ADDRESSTWO` VARCHAR(40) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `CITY` VARCHAR(40) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `STATE` VARCHAR(40) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `ZIPCODE` VARCHAR(40) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `PHONENUMBER` VARCHAR(40) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  PRIMARY KEY (`USERID`),
  CONSTRAINT `FK_addresses_To_users`
    FOREIGN KEY (`USERID`)
    REFERENCES `finalproject`.`users` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `finalproject`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `finalproject`.`products` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `IMG` VARCHAR(40) CHARACTER SET 'utf8' NOT NULL,
  `NAME` VARCHAR(40) CHARACTER SET 'utf8' NOT NULL,
  `PRICE` DECIMAL(10,2) NOT NULL,
  `DESCRIPTION` VARCHAR(40) CHARACTER SET 'utf8' NOT NULL,
  `TAGS` VARCHAR(40) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `finalproject`.`carts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `finalproject`.`carts` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `USERID` INT NOT NULL,
  `PRODUCTID` INT NOT NULL,
  `QUANTITY` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `FK_carts_To_users_idx` (`USERID` ASC) VISIBLE,
  INDEX `FK_carts_To_products_idx` (`PRODUCTID` ASC) VISIBLE,
  CONSTRAINT `FK_carts_To_products`
    FOREIGN KEY (`PRODUCTID`)
    REFERENCES `finalproject`.`products` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_carts_To_users`
    FOREIGN KEY (`USERID`)
    REFERENCES `finalproject`.`users` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
